### ISSUE TITLE
SSIM During Training

### ISSUE THREAD

**Issue by Yuchun-He-1** [zhengchen1999/DAT#28]
Hello,

I want to see the result of SSIM during training, how do I modify the train.py

**Comment by zhengchen1999** [comment]
You don't need to modify the code. Just add 
```
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: True
```
after `test_y_channel: True` in [yml](https://github.com/zhengchen1999/DAT/blob/main/options/Train/train_DAT_x2.yml#L88).
Similar to the [testing yml](https://github.com/zhengchen1999/DAT/blob/main/options/Test/test_DAT_x2.yml#L80).
